version: "2"
services:

    php:
      build: ./docker
      container_name: php5.6_laravel5.4
      volumes:
        - /htdocker/mylaravel-master/laravel5:/var/www/html
      ports:
        - 80:80
      networks:
        - front
        - back
      domainname: laravel.com
      hostname: laravel

    mysql:
      image: mysql:5.7
      container_name: mysql_laravel
      command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--innodb_use_native_aio=0'
     ]
      volumes:
        - /htdocker/mylaravel-master/sql/:/var/lib/mysql
      ports:
        - 3306:3306
      networks:
        - back
      environment:
        - MYSQL_USERNAME=root
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=homestead

    pma:
      image: phpmyadmin/phpmyadmin:4.6
      container_name: pma_laravel
      links:
        - mysql:db
      volumes:
        - /htdocker/mylaravel-master/docker/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      ports:
        - 8888:80
      networks:
        - back
      environment:
        - PMA_ARBITRARY=1

volumes:
    wordpress-db-data:
      driver: local
networks:
  front:
  back: